name: shimmer
description: A lightweight Flutter widget that paints a moving highlight over skeleton placeholders and call-to-action text.
version: 3.0.0
repository: https://github.com/hnvn/flutter_shimmer
issue_tracker: https://github.com/hnvn/flutter_shimmer/issues
contributors: Gregor Weber <The-Redhat>, Vasilliy Ditsyask <vasilich6107>
homepage: https://github.com/hnvn/flutter_shimmer
topics:
  - animation
  - loading
  - shimmer
  - ui

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=1.9.1'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
